const MINUTE = 1000 * 60;

export const CACHE_CONFIG = {
  MAX_ENTRIES: 50,
  MAX_PAGES: 10,
  STALE_TIME: 5 * MINUTE,
  GC_INTERVAL: 10 * MINUTE,
  VERSION: 2,
} as const;

export const STALENESS_PROFILES = {
  REALTIME: 30 * 1000, // 30 seconds
  DEFAULT: CACHE_CONFIG.STALE_TIME,
  LONG_LIVED: 30 * MINUTE,
} as const;
